version: '3.8'

# docker-compose.yml is in a directory called 'web-stack'. 
# The 'example-backend' and 'example-frontend' directories are siblings to the compose file.

# web-stack
# ├───example-backend
# │   ├───...
# │   └───Dockerfile
# ├───example-frontend
# │   ├───...
# │   └───Dockerfile
# └───docker-compose.yml

services:
  frontend:
    build: ./example-frontend
    container_name: frontend
    ports:
      - 5000:5000
  
  backend:
    build: ./example-backend
    container_name: backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres_db
    ports:
      - 8080:8080
    depends_on:
      - db
  
  postgres_db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    container_name: postgres_db

  redis:
    image: redis:latest
    container_name: redis