# DOCKERFILE for example-backend

# Start with an image designed for golang
FROM golang:1.16

WORKDIR /usr/src/app

EXPOSE 8080

# Load the project into the container
COPY . .

ENV REQUEST_ORIGIN=http://localhost

# Run `go build` to generate `server` binary
RUN go build

# Run tests
CMD ["./server"]
